### ISSUE TITLE
a small question

### ISSUE THREAD

**Issue by Tietang999** [czp16/FCSRL#1]
Your paper is excellent,i have a small problem with it,why use TD-lambda to compute return and costs.thanking for your answer.

**Comment by czp16** [comment]
Thanks for your question. TD-lambda can reduce the variance in value function estimation (both for reward and cost). For fair comparison, we also use TD-lambda for all representation learning baselines based on TD3-Lag.

**Comment by Tietang999** [comment]
Thank you for your reply. I wish you success in your research and a happy life!
